disable(rdircd): Third party discord client & doesn't work
This package also not available in most linux distributions package managers. Also not working due to accesing forbidden path.

PermissionError: [Errno 13] Permission denied: '/proc/sys/kernel/random/boot_id'